apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruby-app
  namespace: ruby-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ruby-app
  template:
    metadata:
      labels:
        app: ruby-app
    spec:
      containers:
      - name: ruby-app
        image: ifeanyb/ruby-sinatra-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_HOST
          value: "postgresql"
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: postgres-user
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: postgres-password
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: postgres-db
        - name: DATABASE_PORT
          value: "5432"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5