apiVersion: v1
kind: Service
metadata:
  name: ruby-app-service
  namespace: ruby-app
spec:
  selector:
    app: ruby-app
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP