apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kaniko-fixed
  namespace: ruby-app
spec:
  params:
  - name: IMAGE
    type: string
  - name: DOCKERFILE
    default: ./Dockerfile
    type: string
  - name: CONTEXT
    default: ./
    type: string
  workspaces:
  - name: source
  steps:
  - name: build-and-push
    workingDir: $(workspaces.source.path)
    image: gcr.io/kaniko-project/executor:latest
    args:
    - --dockerfile=$(params.DOCKERFILE)
    - --context=$(workspaces.source.path)/$(params.CONTEXT)
    - --destination=$(params.IMAGE)
    - --skip-tls-verify
    volumeMounts:
    - name: docker-config
      mountPath: /kaniko/.docker
  volumes:
  - name: docker-config
    secret:
      secretName: regcred
      items:
      - key: .dockerconfigjson
        path: config.json
