apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: working-pipeline
  namespace: ruby-app
spec:
  params:
  - name: repo-url
    type: string
  - name: image-reference
    type: string
  workspaces:
  - name: shared-data
  tasks:
  - name: git-clone
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url)
  - name: build-push
    runAfter: ["git-clone"]
    taskRef:
      name: kaniko-fixed
    workspaces:
    - name: source
      workspace: shared-data
    params:
    - name: IMAGE
      value: $(params.image-reference)
    - name: DOCKERFILE
      value: ./app/Dockerfile
    - name: CONTEXT
      value: ./app
