apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: simple-run
  namespace: ruby-app
spec:
  pipelineRef:
    name: simple-pipeline
  params:
  - name: repo-url
    value: https://github.com/MatthewBardi/rails-k8s-gitops.git
  - name: image-reference
    value: ifeanyb/ruby-sinatra-app:simple
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 1Gi
