apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-robot
  namespace: ruby-app
secrets:
- name: regcred
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ruby-app
  name: tekton-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "create", "update", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-rolebinding
  namespace: ruby-app
subjects:
- kind: ServiceAccount
  name: tekton-robot
  namespace: ruby-app
roleRef:
  kind: Role
  name: tekton-role
  apiGroup: rbac.authorization.k8s.io